#!/bin/bash

query=`docker ps | grep ms-postgres`
if [ ${1} == "start" ]; then
    query2=`docker ps -a | grep ms-postgres`
    if [ -z "${query}" ]; then
        if [ -z "${query2}" ]; then
            docker run --name=ms-postgres -d -p 5300:5432 services-postgres
        else
            docker start ms-postgres
        fi
    fi
elif [ ${1} == "stop" ]; then
    if [ ! -z "${query}" ]; then
        docker stop ms-postgres
    fi
elif [ ${1} == "kill" ]; then
    if [ ! -z "${query}" ]; then
        docker rm -f ms-postgres
    fi
elif [ ${1} == "connect" ]; then
    if [ ! -z "${query}" ]; then
        docker exec -it ms-postgres psql micro_services postgres
    fi
fi