#!/bin/bash

cmd=${1}
shift
if [ ${cmd} == "build" ]; then
    ./scripts/buildservices.sh "$@"
elif [ ${cmd} == "start" ]; then
    ./scripts/runservices.sh
elif [ ${cmd} == "stop" ]; then
    ./scripts/stopservices.sh
elif [ ${cmd} == "install" ]; then
    ./scripts/installservices.sh
fi