#!/bin/bash

cmd=${1}
shift
if [ ${cmd} == "build" ]; then
    ./buildservices.sh "$@"
elif [ ${cmd} == "start" ]; then
    ./runservices.sh
elif [ ${cmd} == "stop" ]; then
    ./stopservices.sh
elif [ ${cmd} == "install" ]; then
    ./installservices.sh
fi